name: Build

on: workflow_dispatch

env:
  # Currently, GitHub-hosted runners for public repos specify 4 cores, except macOS 14+
  # See https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/
  #     about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
  CMAKE_BUILD_PARALLEL_LEVEL: 4 # Default only; overridden where appropriate, such as on macOS 14+ below.
  QT_FORCE_STDERR_LOGGING: 1 # Make sure Qt logs errors (during Workflow runs) to console. Especially for Windows.

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Upgrade OS
        run: |
          sudo apt-mark hold firefox grub-efi-amd64-signed
          sudo apt update && sudo apt upgrade
      - name: Install dependencies
        run: |
          sudo apt install --no-install-recommends build-essential cmake git libgnutls28-dev yq
          sudo wget -O ${{ runner.temp }}/appimagecraft.AppImage https://github.com/TheAssassin/appimagecraft/releases/download/continuous/appimagecraft-x86_64.AppImage
          sudo chmod +x ${{ runner.temp }}/appimagecraft.AppImage
      - name: Install online Qt version
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.3
          setup-python: true
          aqtversion: '>=3.2.0' # 3.2.0+ required for Qt 6.8+ support; https://github.com/miurahr/aqtinstall/issues/843
      - name: Upload aqtinstall log file
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: aqtinstall-log-linux
          path: aqtinstall.log
          if-no-files-found: error
      - uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
            export Qt6_ROOT="$QT_ROOT_DIR"
            export QMAKE="$QT_ROOT_DIR/bin/qmake"
            export LD_LIBRARY_PATH="$QT_ROOT_DIR/lib"

            sed -i "s@Qt6_ROOT=.*@Qt6_ROOT=\"$Qt6_ROOT\"@" appimagecraft.yml
            sed -i "s@QMAKE: .*@QMAKE: \"$QMAKE\"@" appimagecraft.yml

            ${{ runner.temp }}/appimagecraft.AppImage
            tee -a "${GITHUB_OUTPUT}" <<< gemImagerVersion=$(yq '.project.version' appimagecraft.yml)
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Gemstone Imager ${{ steps.build.outputs.gemImagerVersion }} Linux
          path: Gemstone_Imager-${{ steps.build.outputs.gemImagerVersion }}-x86_64.AppImage
